### ISSUE TITLE
Minimum SDK 16?

### ISSUE THREAD

**Issue by plackemacher** [novoda/rxpresso#3]
I'm looking into using your library and we currently have our minimum SDK set to 15 which conflicts with this library. Was there any specific reason 16 was chosen? If not, I'll do a pull request to change it to 15.

**Comment by Dorvaryn** [comment]
Good point, there was not particular reason I guess I missed it while extracting this from our sandbox.
I dropped the minSdk to 8 (minimum supported by Espresso) here (https://github.com/novoda/rxpresso/commit/624b010d8a91b5e9be23f404ce5dec470ddbd99f)

If this is not too urgent I'll try and bundle a few other changes I'm experimenting with in a new release. If you are blocked by it I can probably release a minor bump in the meantime.

**Comment by plackemacher** [comment]
Great thanks! This isn't particularly urgent so feel free to take your time on the release.

**Comment by Dorvaryn** [comment]
@plackemacher it was taking me a bit longer than expected to polish what I wanted in so in the meantime release 0.1.5 is out with lowered minSDK version.

**Comment by plackemacher** [comment]
Awesome, thanks for the heads up. :+1:
