### ISSUE TITLE
minSdk 16 instead of 8 (according to GitHub) with gradle

### ISSUE THREAD

**Issue by OzoTek** [novoda/rxpresso#4]
Hello, I tried to import RxPresso 0.1.4 with gradle : jcenter() and my project is for a minimum sdk of 15.
After the sync, I get the error : 
Error:(5, 5) uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library app/build/intermediates/exploded-aar/com.novoda/rxpresso/0.1.4/AndroidManifest.xml 

The problem is, according to your last push, the minimum sdk required changed to 8, so why do I still have this issue ?

Thank you !

**Comment by rock3r** [comment]
The `minSdkVersion` change has been pushed [last week](https://github.com/novoda/rxpresso/commit/4ce2a7b2c07d946113ec8571d31dea2459fe14a4). Version 0.1.4 has been released in [mid-May](https://github.com/novoda/rxpresso/commit/624b010d8a91b5e9be23f404ce5dec470ddbd99f). You'll have to either use the library from sources or wait for the next version to be released.

**Comment by OzoTek** [comment]
Oh okay, I thought it was deployed, sorry.
Thank you for your quick answer.

**Comment by rock3r** [comment]
No worries.

**Comment by Dorvaryn** [comment]
@OzoTek It is obvious that it is taking me longer than expected to polish the new features I wanted in the next release of RxPresso. I'll issue a new minor release in the meantime just to cover this minSdk issue.

**Comment by Dorvaryn** [comment]
@oeoTek release 0.1.5 is out with lowered minSDK version.

**Comment by OzoTek** [comment]
Nice thank you for that ! Good luck for your next release :+1:
